trigger:
- master

jobs:
- job: MacOS
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: dotnet restore
    displayName: 'Restore dependencies'
  - script: dotnet build
    displayName: Build

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build
    displayName: 'Build'

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build
    displayName: 'Build'

- job: Publish
  dependsOn:
  - MacOS
  - Windows
  - Linux

  pool:
    vmImage: 'Ubuntu 16.04'
  
  steps:
  - script: dotnet restore
    displayName: 'Restoring Packages'

  - script: dotnet build --configuration Debug --version-suffix $(Build.BuildNumber)
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/release')
    displayName: 'Building'

  - script: dotnet build --configuration Release
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/release')
    displayName: 'Building (Release)'

  - task: NuGetCommand@2
    displayName: 'Publishing Build'
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/release')))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'Copren.NuGet'
      packagesToPush: './**/*.nupkg'
